# https://json.schemastore.org/github-action.json

name: .NET Test

on:
  pull_request: 
    types: [opened, synchronize, reopened]
  push:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - run: dotnet build
      - run: dotnet test
